<script lang="ts">
</script>

<svelte:head>
  <title>Terms of Service | Cascade</title>
</svelte:head>

<div class="min-h-screen bg-neutral-950 py-20">
  <div class="max-w-3xl mx-auto px-6">
    <h1 class="text-4xl font-bold text-white mb-4">Terms of Service</h1>
    <p class="text-neutral-500 text-sm mb-10">Last Updated: April 5, 2026</p>

    <div class="space-y-8 text-neutral-300 leading-relaxed">
      <section>
        <h2 class="text-xl font-semibold text-white mt-10 mb-4">1. About Cascade</h2>
        <p>
          Cascade is a decentralized prediction market platform built on Nostr, a censorship-resistant communication protocol. Our platform enables users to create markets on future events and trade shares based on predictions. Cascade uses Cashu ecash tokens for trading, providing privacy-preserving transactions.
        </p>
      </section>

      <section>
        <h2 class="text-xl font-semibold text-white mt-10 mb-4">2. Eligibility</h2>
        <p>
          You must be at least 18 years old, or the legal age of majority in your jurisdiction, to use Cascade. By using this platform, you represent that you meet these requirements and have the legal capacity to enter into these terms.
        </p>
      </section>

      <section>
        <h2 class="text-xl font-semibold text-white mt-10 mb-4">3. Account and Identity</h2>
        <p>
          Cascade uses Nostr for identity management. Your account is represented by your Nostr public key, which is generated by your Nostr signer or wallet extension. You control your own keys—this means you are solely responsible for their security and any actions taken with them.
        </p>
        <p class="mt-4">
          We do not have the ability to reset or recover your keys. If you lose access to your keys, you lose access to your account and any associated data on the platform.
        </p>
      </section>

      <section>
        <h2 class="text-xl font-semibold text-white mt-10 mb-4">4. Market Creation and Trading</h2>
        <p>
          Cascade uses a Liquidity-Sensitive Market Maker (LMSR) mechanism for trading. Users can create markets on various topics and trade Yes/No shares. Market prices reflect the collective belief about outcome probabilities.
        </p>
        <p class="mt-4">
          All trades are executed using Cashu ecash tokens. When you trade, you interact with Cashu mints for payment settlement. Cascade facilitates the trading interface but does not hold or control your funds directly.
        </p>
      </section>

      <section>
        <h2 class="text-xl font-semibold text-white mt-10 mb-4">5. Beta and Demo Phase</h2>
        <p>
          Cascade is currently in beta and demo phase. There is no guarantee of continuous availability, and the platform may experience downtime, bugs, or unexpected behavior. Market data and balances may be reset or modified during this phase.
        </p>
        <p class="mt-4">
          No real money currently flows on the platform—trading uses demo tokens. When real value is introduced, these terms will be updated accordingly.
        </p>
      </section>

      <section>
        <h2 class="text-xl font-semibold text-white mt-10 mb-4">6. No Financial Advice</h2>
        <p>
          Nothing on Cascade constitutes financial, legal, or investment advice. Prediction markets are for entertainment and informational purposes only. The prices of shares reflect crowd sentiment and are not guarantees of outcomes. You are responsible for your own decisions and should conduct your own research before making any trades.
        </p>
      </section>

      <section>
        <h2 class="text-xl font-semibold text-white mt-10 mb-4">7. Intellectual Property</h2>
        <p>
          When you create a market on Cascade, your content (market descriptions, titles, and associated metadata) is published to Nostr relays as public events. This content becomes part of the public Nostr ecosystem and can be viewed, shared, and archived by anyone.
        </p>
        <p class="mt-4">
          Cascade's name, logo, and original code remain the property of the project. You retain ownership of your contributions but grant the platform and other users the ability to interact with your content as enabled by the Nostr protocol.
        </p>
      </section>

      <section>
        <h2 class="text-xl font-semibold text-white mt-10 mb-4">8. User Conduct</h2>
        <p>
          You agree not to use Cascade for illegal purposes, market manipulation, or any activity that harms other users or the platform. Market creators are responsible for the accuracy and appropriateness of their markets. Markets containing false information, hate speech, or illegal content may be subject to removal.
        </p>
      </section>

      <section>
        <h2 class="text-xl font-semibold text-white mt-10 mb-4">9. Limitation of Liability</h2>
        <p>
          Cascade is provided "as is" without warranties of any kind. We do not guarantee the accuracy of market information, continuous availability, or error-free operation. To the fullest extent permitted by law, we are not liable for any indirect, incidental, or consequential damages arising from your use of the platform.
        </p>
        <p class="mt-4">
          In the event of technical failures, relay outages, or data loss on Nostr, we bear no responsibility for recovering lost data or compensating for disruptions.
        </p>
      </section>

      <section>
        <h2 class="text-xl font-semibold text-white mt-10 mb-4">10. Dispute Resolution</h2>
        <p>
          These terms are governed by the principles of good faith and fair dealing. Any disputes arising from the use of Cascade should first be addressed through direct communication. Given the decentralized nature of Nostr, traditional legal venues may have limited jurisdiction over platform-related disputes.
        </p>
      </section>

      <section>
        <h2 class="text-xl font-semibold text-white mt-10 mb-4">11. Modification of Terms</h2>
        <p>
          We reserve the right to update these terms at any time. Changes will be posted on this page with an updated "Last Updated" date. Continued use of the platform after changes constitutes acceptance of the new terms.
        </p>
      </section>

      <section>
        <h2 class="text-xl font-semibold text-white mt-10 mb-4">12. Contact</h2>
        <p>
          For questions about these terms or the platform, reach out via Nostr:
        </p>
        <p class="mt-2">
          <a 
            href="https://njump.me/npub1jfmfh0hj0g4qgv3l0aez0w8unsn73c7n6lhrgn3x40x4g0n5mkqsz8x3y5" 
            target="_blank"
            rel="noopener noreferrer"
            class="text-emerald-500 hover:text-emerald-400"
          >
            npub1jfmfh0hj0g4qgv3l0aez0w8unsn73c7n6lhrgn3x40x4g0n5mkqsz8x3y5
          </a>
        </p>
      </section>
    </div>

    <div class="mt-16 pt-8 border-t border-neutral-800">
      <a 
        href="/" 
        class="text-neutral-400 hover:text-white transition-colors"
      >
        ← Back to Home
      </a>
    </div>
  </div>
</div>
